import { StyleSheet } from "react-native";
import { color } from "react-native-reanimated";
import { Dimensions } from "react-native";
export const gStyle = StyleSheet.create({
  tabNav: {
    backgroundColor: "#38354B",
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 30,
  },
  textTabBar: {
    justifyContent: "center",
    alignItems: "center",
    padding: 25,
  },
  container: {
    flex: 1,
    backgroundColor: "#1C1A29",
  },
  headerText: {
    color: "#DEDDDF",
    fontSize: 21,
    marginTop: 15,
    marginLeft: 15,
  },
  image: {
    width: 40,
    height: 40,
  },
  containerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 15,
    paddingLeft: 15,
  },
  searchEtd: {
    paddingTop: 25,
    alignItems: "flex-end",
    flexDirection: "row",
  },
  elementsHeader: {
    paddingRight: 15,
  },
  logoHeader: {
    paddingTop: 15,
  },
  popularImg: {
    width: 150,
    height: 200,
  },
  titleHomeScreen: {
    color: "#DEDDDF",
    fontSize: 12,
    fontFamily: "Open Sans",
  },
  backgroundImage: {
    width: 400,
    height: 220,
    resizeMode: "cover",
    marginTop: 10,
    marginLeft: 7,
  },
  posterImage: {
    width: 150,
    height: 240,
    marginLeft: 15,
    zIndex: 1,
    resizeMode: "cover",
  },
  textExtensions: {
    color: "#777777",
    fontSize: 15,
    marginTop: 15,
    marginRight: 15,
  },
  containerListText: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: 15,
    paddingBottom: 10,
  },
  titleMovies: {
    color: "#fff",
    fontSize: 12,
    textAlign: "center",
    width: 150,
    marginLeft: 15,
  },
  movieCard: {
    width: 150,
    height: 240,
    marginLeft: 5,
    marginRight: 5,
  },
  avatarImage: {
    width: 150,
    height: 150,
    resizeMode: "contain",
    borderRadius: 120,
  },
  textUserName: {
    color: "#fff",
    textAlign: "center",
    fontSize: 24,
  },
  textUserEmail: {
    fontSize: 14,
    color: "#A8A8A8",
  },
  containerUserInfo: {
    flexDirection: "row",
    alignContent: "center",
    margin: 15,
  },
  textUserContainer: {
    alignContent: "center",
    padding: 30,
  },
  backgroundMovieScreen: {
    width: 450,
    height: 400,
    opacity: 0.5,
  },
  posterMovieScreen: {
    width: 140,
    height: 170,
    position: "absolute",
    marginTop: 205,
    zIndex: 1,
    resizeMode: "contain",
    alignItems: "flex-end",
    right: 0,
  },
  titleMoviesScreen: {
    position: "absolute",
    zIndex: 1,
    marginTop: 210,
    color: "white",
    marginLeft: 15,
    fontSize: 21,
    width: 270,
  },
  companyMoviesScreen: {
    position: "absolute",
    zIndex: 1,
    marginTop: 267,
    color: "#777777",
    marginLeft: 15,
    fontSize: 15,
  },
  release_date: {
    position: "absolute",
    marginTop: 220,
    zIndex: 1,
    marginLeft: 27,
    fontSize: 15,
    color: "#DEDDDF",
  },
  starVote: {
    width: 16,
    height: 16,
    marginRight: 5,
    resizeMode: "contain",
  },
  voteStar: {
    flexDirection: "row",
    position: "absolute",
    zIndex: 1,
    marginTop: 295,
    marginLeft: 15,
  },
  raiting: {
    color: "#777777",
  },

  titleSinopsis: {
    color: "#DEDDDF",
    fontSize: 21,
    marginLeft: 15,
  },
  textSinopsis: {
    color: "#DEDDDF",
    marginLeft: 15,
  },
  trailerText: {
    color: "#DEDDDF",
    fontSize: 21,
    marginLeft: 15,
    paddingTop: 15,
    paddingBottom: 15,
  },
  profileActor: {
    width: 100,
    height: 150,
    resizeMode: "contain",
    alignContent: "center",
    marginLeft: 5,
  },
  actorList: {
    color: "#fff",
    fontSize: 12,
    textAlign: "center",
    width: 100,
  },
  characrerList: {
    color: "#777",
    fontSize: 12,
    textAlign: "center",
    width: 100,
  },
  videotrailer: {
    width: "100%",
    height: 300,
    paddingTop: 20,
    resizeMode: "contain",
  },
  avatarComments: {
    width: 70,
    height: 70,
    margin: 5,
    borderRadius: 20,
  },
  commentsText: {
    color: "#fff",
  },
  nameComments: {
    color: "#DEDDDF",
  },
  commentsHeader: {
    color: "white",
    flexDirection: "row",
    textAlign: "center",
    alignItems: "center",
    borderBottomColor: "#7F7D88",
  },
  commentsList: {
    marginLeft: 15,
    color: "#fff",
    flex: 1,
    zIndex: 2,
  },
  ExplorerTitleMovies: {
    color: "white",
    fontSize: 18,
    width: 240,
    paddingTop: 15,
    marginLeft: 5,
  },
  blockMovies: {
    flexDirection: "row",
    paddingBottom: 15,
  },
  searchInput: {
    borderColor: "#fff",
    borderWidth: 1,
    margin: 15,
    height: 50,
    padding: 10,
    color: "#FFFFFF",
  },
  inputDataAutho: {
    borderColor: "#A8A8A8",
    borderWidth: 1,
    color: "#fff",
    margin: 15,
    padding: 15,
    borderRadius: 5,
  },
  containerAuth: {
    paddingTop: 50,
    alignItems: "center",
  },
  imageRegistration: {
    width: 100,
    height: 100,
    alignItems: "center",
  },
  buttonReg: {
    color: "#000",
  },
  textInputContainer: {
    marginBottom: 50,
    marginTop: 50,
  },
  containerForComments: {
    margin: 25,
    backgroundColor: "#242135",
  },
  listActor: {
    position: "absolute",
    marginTop: 315,
    color: "#777777",
    marginLeft: 15,
    width: 230,
  },
  chatTitleHeader: {
    color: "white",
    textAlign: "center",
    fontSize: 20,
    paddingTop: 20,
  },
  chatMessageBox: {
    color: "white",
  },
  containerChatMessage: {
    flexDirection: "row",
    borderRadius: 10,
    margin: 10,
    position: "relative",
  },
  chatUser: {
    color: "#969594",
    fontSize: 18,
  },
  containerUserData: {
    flexDirection: "row",
    textAlign: "center",
    width: "70%",
  },
  containerChat: {
    backgroundColor: "#242135",
    margin: 7,
    borderRadius: 10,
    borderBottomColor: "#000",
    borderBottomWidth: 1,
  },
  inputMessage: {
    position: "relative",
    bottom: 0,
    borderColor: "#a8a8a8",
    borderWidth: 1,
    margin: 15,
    padding: 15,
    color: "#FFFFFF",
    borderRadius: 4,
  },
  avatarUser: {
    width: 150,
    height: 150,
    resizeMode: "contain",
  },
  containerforUser: {
    flexDirection: "row",
    marginTop: 25,
    marginLeft: 15,
  },
  nameEmail: {
    marginTop: 25,
    marginLeft: 25,
  },
  nameUser: {
    color: "#fff",
    fontSize: 24,
  },
  emailUser: {
    color: "#a8a8a8",
    fontSize: 14,
  },
  buttonChangeImage: {
    color: "#EF3A01",
    marginBottom: 25,
    marginLeft: 20,
  },
  containerbtn: {
    margin: 15,
  },
  time: {
    color: "#969594",
    marginLeft: "auto",
    alignSelf: "flex-end",
  },
  search: {
    margin: 15,
  },
  listActorExplorer: {
    color: "white",
    fontSize: 14,
    width: 240,
    paddingTop: 15,
    marginLeft: 5,
  },
  company: {
    color: "white",
    fontSize: 12,
    width: 240,
    paddingTop: 15,
    marginLeft: 5,
  },
  year: {
    color: "white",
    fontSize: 12,
    width: 240,
    paddingTop: 15,
    marginLeft: 5,
  },
  newsImage: {
    width: "100%",
    height: 200,
    resizeMode: "cover",
    borderRadius: 10,
    opacity: 0.4,
  },
  titleNews: {
    position: "absolute",
    color: "white",
    marginTop: 20,
    lineHeight: 18,
    padding: 20,
  },
  dataNews: {
    position: "absolute",
    color: "white",
    alignContent: "flex-end",
    marginTop: 120,
    padding: 20,
  },
  imageNewsDetail: {
    width: "100%",
    height: 250,
    resizeMode: "contain",
    alignContent: "center",
  },
  titlenewsDetail: {
    color: "white",
    marginLeft: 20,
    fontSize: 20,
    textAlign: "center",
  },
  newsContainer: {
    height: "100%",
    flexDirection: "row",
  },
  newsDesc: {
    color: "white",
  },
  dateNews: {
    textAlign: "right",
    margin: 10,
    color: "white",
  },
  containerNews: {
    margin: 10,
  },
  containerTime: {
    display: "flex",
    flexDirection: "column",
    width: "75%",
  },
});
